language: minimal
sudo: true
branches:
only:
 - master # build master branch only
before_script: 
 - sudo apt-get -qq update
 - sudo apt-get -y install texlive
 - sudo tlmgr option repository https://mirrors.tuna.tsinghua.edu.cn/CTAN/systems/texlive/tlnet
 - 
script: 
 - pdflatex -synctex=1 -interaction=nonstopmode Project.tex
deploy:
 provider: releases
 api_key: $GH_TOKEN
 file: "Project.tex"
 skip_cleanup: true