language: generic
sudo: required
install: sudo apt-get install texlive-full
script: pdflatex -synctex=1 -interaction=nonstopmode Project.tex
deploy:
	provider: releases
	api_key: $GITHUB_TOKEN
	file: "Project.tex"
	skip_cleanup: true