language: generic
sudo: required
sudo: true
language: generic
branches:
  only:
    - master # build master branch only
install: 
  - sudo apt-get install texlive-full
script: 
  - pdflatex -synctex=1 -interaction=nonstopmode Project.tex
deploy:
	provider: releases
	api_key: $GH_TOKEN
	file: "Project.tex"
	skip_cleanup: true